from __future__ import annotations


STATUS_NEW = "未联系"
STATUS_DRAFTED = "已生成开发信"
STATUS_REVIEW = "待人工审核"
STATUS_SENT = "已发送"
STATUS_REPLIED = "已回复"
STATUS_FOLLOWING = "跟进中"
STATUS_INVALID = "无效客户"
STATUS_WON = "已成交"

DRAFT_STATUS_PENDING = "待审核"
DRAFT_STATUS_APPROVED = "已通过"

REPLY_STATUS_NONE = ""
REPLY_STATUS_REPLIED = "客户已回复"
REPLY_STATUS_AUTO_REPLY = "自动回复"
REPLY_STATUS_BOUNCED = "邮件退信"
REPLY_STATUS_REJECTED = "拒绝沟通"

STATUS_OPTIONS = [
    STATUS_NEW,
    STATUS_DRAFTED,
    STATUS_REVIEW,
    STATUS_SENT,
    STATUS_REPLIED,
    STATUS_FOLLOWING,
    STATUS_INVALID,
    STATUS_WON,
]

REPLY_STATUS_OPTIONS = [
    REPLY_STATUS_REPLIED,
    REPLY_STATUS_AUTO_REPLY,
    REPLY_STATUS_BOUNCED,
    REPLY_STATUS_REJECTED,
]
